# The 'address' option : binds to the specified IP.
# The 'port' option : the number of server ports
# The 'dir' option :  The directory in cloud-config file out of which you will serve your.

address: 0.0.0.0
port: 80
dir: /usr/local/my-hosts/
vault: none
